language: rust
rust:
  - stable
  - nightly
matrix: 
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --release --verbose --all
  - cargo test --verbose --all