[package]
name = "rugenere"
version = "0.2.0"
authors = ["Bruno Anjos <bruno.vale.anjos@gmail.com>"]
edition = "2018"

[lib]
name = "rugenere"
path = "src/lib.rs"

[[bin]]
name = "rugenere"
path = "src/main.rs"

[dependencies]
clap = {version = "~2.33", features = ["yaml"]}
